// src/components/UI/Creature.vue
<script setup lang="ts">
    import type Creature from '~/lib/Models/Creature'
    import ProgressBar from "~/components/ProgressBar.vue"

    defineOptions({
        name: 'Creature',
    })

    const props = defineProps<{
        creature: Creature
        acting?: boolean
    }>()

    const commandStack = computed(() => props.creature.commandStack)
    const commandHistory = computed(() => props.creature.commandHistory)
    const lastCommandHistory = computed(() => commandHistory.value.slice(-10))
</script>

<template>
    <div class="flex flex-col gap-x-12">
        <div
            class="bg-blue-100 rounded-lg p-8 border-2"
            :class="acting ? 'border-blue-500' : ' border-blue-100'"
        >
            <div class="text-lg font-bold text-gray-600 mb-8">
                {{ creature.name }}
            </div>

            <div class="flex flex-col gap-4">
                <div class="w-full flex flex-col gap-1">
                    <div v-if="creature.maxHealth !== undefined">
                        {{ creature.health }} / {{ creature.maxHealth }}
                        <ProgressBar color="bg-red-400" :progress="creature.health" :max="creature.maxHealth" />
                    </div>

                    <div v-if="creature.maxMana !== undefined">
                        {{ creature.mana }} / {{ creature.maxMana }}
                        <ProgressBar color="bg-blue-400" :progress="creature.mana" :max="creature.maxMana" />
                    </div>
                </div>

                <div class="grid grid-cols-3 gap-4 text-center">
                    <div :class="{ 'opacity-30': !creature.stats.strength }">
                        <i class="fa-solid fa-hand-fist" /> {{ creature.stats.strength }}
                    </div>
                    <div :class="{ 'opacity-30': !creature.stats.agility }">
                        <i class="fa-solid fa-hourglass" /> {{ creature.stats.agility }}
                    </div>
                    <div :class="{ 'opacity-30': !creature.stats.intelligence }">
                        <i class="fa-solid fa-book" /> {{ creature.stats.intelligence }}
                    </div>
                </div>
            </div>
        </div>
        <div class="flex flex-col gap-4">
            <div v-if="commandStack.length">
                <div class="text-gray-500 text-sm">
                    Casting:
                </div>
                <div>
                    {{ commandStack.join(' > ') }}
                </div>
            </div>

            <div v-if="lastCommandHistory.length" class="text-gray-500 text-xs">
                History:
                <div v-for="(command, $i) in lastCommandHistory" :key="$i" class="text-gray-400">
                    {{ command }}
                </div>
            </div>
        </div>
    </div>
</template>

// src/components/Creature.svelte
<script lang="ts">
    import type Creature from '~/lib/Models/Creature'
    import ProgressBar from '~/components/ProgressBar.svelte'

    export let creature: Creature
    export let acting = false

    let lastCommandHistory
    $: lastCommandHistory = commandHistory.slice(-10)

    let commandStack
    $: commandStack = creature?.commandStack

    let commandHistory
    $: commandHistory = creature?.commandHistory
</script>

<div class={($$restProps['class'] ?? '') + ' flex gap-x-12'}>
    <div class={'bg-blue-100 rounded-lg p-8 w-80 border-2 rounded ' + (acting ? 'border-blue-500' : ' border-blue-100')}>
        <div class="text-lg font-bold text-gray-600 mb-8">{creature.name}</div>

        <div class="flex flex-col gap-4">
            <div class="w-full flex flex-col gap-1">
                <ProgressBar color="bg-red-400" value={creature.health} maxValue={creature.maxHealth}/>
                <ProgressBar color="bg-blue-500" value={creature.mana} maxValue={creature.maxMana}/>
            </div>

            <div class="grid grid-cols-3 gap-4 text-center">
                <div class="" class:opacity-30={!creature.stats.strength}>
                    <i class="fa-solid fa-hand-fist"></i> {creature.stats.strength}
                </div>
                <div class="" class:opacity-30={!creature.stats.agility}>
                    <i class="fa-solid fa-hourglass"></i> {creature.stats.agility}
                </div>
                <div class="" class:opacity-30={!creature.stats.intelligence}>
                    <i class="fa-solid fa-book"></i> {creature.stats.intelligence}
                </div>
            </div>
        </div>
    </div>
    <div class="flex flex-col gap-4">
        {#if commandStack.length}
            <div>
                <div class="text-gray-500 text-sm">Casting:</div>
                <div>
                    {commandStack.join(' > ')}
                </div>
            </div>
        {/if}

        {#if lastCommandHistory.length}
            <div class="text-gray-500 text-xs">
                History:
                {#each lastCommandHistory as command}
                    <div class="text-gray-400">{command}</div>
                {/each}
            </div>
        {/if}
    </div>
</div>
