// src/components/ProgressBar.vue
<template>
    <div class="w-full text-sm">
        <div class="w-full bg-gray-300 rounded font-normal">
            <div
                class="rounded text-xs leading-none pt-1 text-center text-white whitespace-no-wrap"
                :style="{width: percent + '%'}"
                :class="color"
            />
        </div>
    </div>
</template>

<script setup lang="ts">
    const props = withDefaults(defineProps<{
        progress: number,
        max?: number,
        color?: string,
    }>(), {
        max: undefined,
        color: 'bg-blue-400',
    })

    const percent = computed(() => {
        if (props.max) {
            return props.progress / props.max * 100
        }

        return props.progress * 100
    })
</script>

// src/components/ProgressBar.svelte
<script lang="ts">
    export let value: number = 0;
    export let maxValue: number = 100;

    export let color: string;

    let progress
    $: progress = Math.min(100, Math.max(0, value / maxValue * 100)) + '%';
</script>

{#if maxValue > 0}
    <div class="bg-gray-300 leading-none p-[2px] relative overflow-hidden rounded-lg w-full">
        <div class="text-[0.65rem] text-center relative z-[1]">{value} / {maxValue}</div>
        <div class={color + ' absolute top-0 left-0 h-full'} style={`width: ${progress}`}></div>
    </div>
{/if}
